version: "3"

services:
    backend:
        image: raphaelmue/raphael-muesseler-backend:latest
        container_name: raphael-muesseler-backend
        restart: always
        ports:
            - 1337:1337
        volumes:
            - ./data.db:/usr/src/app/.data/data.db
        environment:
            SMTP_HOST=host
            SMTP_PORT=465
            SMTP_USERNAME=username
            SMTP_PASSWORD=password

    frontend:
        image: raphaelmue/raphael-muesseler-frontend:latest
        container_name: raphael-muesseler-frontend
        restart: always
        ports:
            - 3001:3001
        links:
            - backend
        volumes:
            - ./config.js:/usr/share/nginx/html/config.js
